CREATE TABLE `session_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`tags` text,
	`selectedModel` enum('codex','claude','gemini','manus') NOT NULL DEFAULT 'claude',
	`selectedProfile` enum('patch_goblin','architect_owl','test_gremlin','refactor_surgeon') NOT NULL DEFAULT 'patch_goblin',
	`ralphMode` boolean NOT NULL DEFAULT true,
	`maxIterations` int NOT NULL DEFAULT 50,
	`noProgressThreshold` int NOT NULL DEFAULT 3,
	`autoAskHuman` boolean NOT NULL DEFAULT true,
	`safetyMode` enum('standard','strict','permissive') NOT NULL DEFAULT 'standard',
	`promptGoal` text,
	`promptContext` text,
	`promptDoneWhen` text,
	`promptDoNot` text,
	`completionCriteria` text,
	`usageCount` int NOT NULL DEFAULT 0,
	`lastUsedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `session_templates_id` PRIMARY KEY(`id`)
);
