#!/bin/bash
#
# USDR OpenWebRX+ Integration Installation Script
#
# This script automates the installation of USDR device support for OpenWebRX+.
#
# Usage:
#   chmod +x install_usdr_openwebrx.sh
#   sudo ./install_usdr_openwebrx.sh
#
# Prerequisites:
#   - OpenWebRX+ must be installed
#   - Ubuntu 20.04 or later (for PPA support)
#
# Copyright (c) 2025
# SPDX-License-Identifier: MIT

set -e

echo "=================================================="
echo "USDR OpenWebRX+ Integration Installer"
echo "=================================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

# Detect OpenWebRX+ installation path
OWRX_SOURCE_PATH=""
if [ -d "/usr/lib/python3/dist-packages/owrx/source" ]; then
    OWRX_SOURCE_PATH="/usr/lib/python3/dist-packages/owrx/source"
elif [ -d "/opt/openwebrx/owrx/source" ]; then
    OWRX_SOURCE_PATH="/opt/openwebrx/owrx/source"
else
    echo "Error: Could not find OpenWebRX+ installation"
    echo "Please ensure OpenWebRX+ is installed before running this script"
    exit 1
fi

OWRX_FEATURE_PATH=$(dirname "$OWRX_SOURCE_PATH")/feature.py

echo "Detected OpenWebRX+ source path: $OWRX_SOURCE_PATH"
echo "Detected OpenWebRX+ feature path: $OWRX_FEATURE_PATH"
echo ""

# Step 1: Install usdr-lib and SoapySDR module
echo "Step 1: Installing usdr-lib and SoapySDR module..."
echo ""

if ! command -v add-apt-repository &> /dev/null; then
    apt-get update
    apt-get install -y software-properties-common
fi

add-apt-repository -y ppa:wavelet-lab/usdr-lib
apt-get update
apt-get install -y usdr-tools soapysdr-module-usdr libusdr-dev

echo ""
echo "Step 1 complete: usdr-lib installed"
echo ""

# Step 2: Verify SoapySDR installation
echo "Step 2: Verifying SoapySDR installation..."
echo ""

if command -v SoapySDRUtil &> /dev/null; then
    echo "SoapySDR modules:"
    SoapySDRUtil --info 2>/dev/null | grep -A 100 "Available factories" || true
    echo ""
    
    # Check if usdr driver is available
    if soapy_connector --listdrivers 2>/dev/null | grep -q "usdr"; then
        echo "✓ USDR driver detected in soapy_connector"
    else
        echo "⚠ Warning: USDR driver not detected in soapy_connector"
        echo "  You may need to restart the system or check the installation"
    fi
else
    echo "⚠ Warning: SoapySDRUtil not found"
fi

echo ""
echo "Step 2 complete: SoapySDR verification done"
echo ""

# Step 3: Install USDR device file
echo "Step 3: Installing USDR device file..."
echo ""

cat > "$OWRX_SOURCE_PATH/usdr.py" << 'EOF'
# USDR (Wavelet Lab Micro SDR) Device Support for OpenWebRX+
# Auto-generated by install_usdr_openwebrx.sh

from owrx.source.soapy import SoapyConnectorSource, SoapyConnectorDeviceDescription
from owrx.form.input import Input, NumberInput
from owrx.form.input.validator import RangeValidator, Range
from typing import List


class UsdrSource(SoapyConnectorSource):
    def getDriver(self):
        return "usdr"
    
    def getSoapySettingsMappings(self):
        mappings = super().getSoapySettingsMappings()
        mappings.update({
            "loglevel": "loglevel",
            "rx_bw": "rx_bw",
            "tx_bw": "tx_bw",
        })
        return mappings


class UsdrDeviceDescription(SoapyConnectorDeviceDescription):
    def getName(self):
        return "USDR (Wavelet Lab Micro SDR)"
    
    def getInputs(self) -> List[Input]:
        return super().getInputs() + [
            NumberInput(
                "loglevel",
                "Log level",
                infotext="Set the logging verbosity level (0-5, default: 3)",
                validator=RangeValidator(0, 5),
            ),
            NumberInput(
                "rx_bw",
                "RX Bandwidth",
                append="Hz",
                infotext="Set the receive bandwidth filter",
            ),
        ]
    
    def getDeviceOptionalKeys(self):
        return super().getDeviceOptionalKeys() + ["loglevel", "rx_bw"]
    
    def getProfileOptionalKeys(self):
        return super().getProfileOptionalKeys() + ["rx_bw"]
    
    def getSampleRateRanges(self) -> List[Range]:
        return [Range(100000, 65000000)]
    
    def getGainStages(self):
        return ["LNA", "VGA1", "VGA2"]
    
    def hasAgc(self):
        return False
EOF

echo "✓ USDR device file installed to $OWRX_SOURCE_PATH/usdr.py"
echo ""
echo "Step 3 complete: USDR device file installed"
echo ""

# Step 4: Patch feature.py
echo "Step 4: Patching feature.py for USDR support..."
echo ""

# Backup original feature.py
cp "$OWRX_FEATURE_PATH" "$OWRX_FEATURE_PATH.backup"
echo "✓ Backup created: $OWRX_FEATURE_PATH.backup"

# Check if usdr is already in features
if grep -q '"usdr"' "$OWRX_FEATURE_PATH"; then
    echo "✓ USDR already present in feature.py"
else
    # Add usdr to features dictionary
    sed -i '/\"sdrplay\":/a\        "usdr": ["soapy_connector", "soapy_usdr"],' "$OWRX_FEATURE_PATH"
    echo "✓ Added USDR to features dictionary"
fi

# Check if has_soapy_usdr method exists
if grep -q 'has_soapy_usdr' "$OWRX_FEATURE_PATH"; then
    echo "✓ has_soapy_usdr method already present"
else
    # Add has_soapy_usdr method after has_soapy_sdrplay
    sed -i '/def has_soapy_sdrplay/,/return self._has_soapy_driver("sdrplay")/a\
\
    def has_soapy_usdr(self):\
        """\
        The [SoapySDR module for USDR](https://github.com/wavelet-lab/usdr-lib)\
        is required for interfacing with Wavelet Lab uSDR devices.\
        """\
        return self._has_soapy_driver("usdr")' "$OWRX_FEATURE_PATH"
    echo "✓ Added has_soapy_usdr method"
fi

echo ""
echo "Step 4 complete: feature.py patched"
echo ""

# Step 5: Restart OpenWebRX+
echo "Step 5: Restarting OpenWebRX+ service..."
echo ""

if systemctl is-active --quiet openwebrx; then
    systemctl restart openwebrx
    echo "✓ OpenWebRX+ service restarted"
else
    echo "⚠ OpenWebRX+ service not running, skipping restart"
fi

echo ""
echo "=================================================="
echo "Installation Complete!"
echo "=================================================="
echo ""
echo "Next steps:"
echo "1. Connect your USDR device"
echo "2. Verify device detection: SoapySDRUtil --probe=\"driver=usdr\""
echo "3. Add USDR device in OpenWebRX+ settings (web interface or settings.yaml)"
echo "4. Access OpenWebRX+ at http://localhost:8073/"
echo ""
echo "Example settings.yaml configuration:"
echo ""
echo "sdr_devices:"
echo "  usdr:"
echo "    type: usdr"
echo "    name: \"USDR\""
echo "    device: \"driver=usdr\""
echo "    profiles:"
echo "      default:"
echo "        name: \"Default\""
echo "        center_freq: 433000000"
echo "        samp_rate: 2048000"
echo ""
echo "For troubleshooting, check: journalctl -u openwebrx -f"
echo ""
